---
title: "Autoencoders basics"
author: "Anastasios Vlaikidis"
date: "3/30/2022"
output: html_document
---

```{r}
library(keras)
```


## Sample data

```{r}
set.seed(1821)

df <- d %>% slice_sample(prop = .005)



dim(df)

df <-
  df %>% 
  mutate(Target = if_else(Target == 0, "Smooth","Anomaly") %>% 
  as.factor() %>% 
  relevel(ref = "Smooth"))

df %>% class
```

## Train , Test splits
```{r}

df_split <- initial_split(
  
  df, 
  prop = .75,
  strata = Target
  
)



df_train <- training(df_split)
df_test <- testing(df_split)

df_train <- df_train[sample(1:nrow(df_train)),]
df_test <- df_test[sample(1:nrow(df_test)),]

# basic preprocess
basic_rec <-
  recipe(Target~., data = df_train) %>%
  # step_YeoJohnson(all_numeric_predictors()) %>%
  # step_normalize(all_numeric_predictors())
  step_range(all_numeric_predictors())


# apply the recipe to the train and test data
df_train <-
  basic_rec %>%
  prep() %>%
  bake(new_data = df_train)


df_test <-
  basic_rec %>%
  prep() %>%
  bake(new_data = df_test)
```


```{r}
df_train %>% class()
df_test %>% class() 
```


```{r}
train_x <- df_train %>% select(-Target)
Target_train_y <- df_train$Target

test_x <- df_test %>% select(-Target)
Target_test_y <- df_test$Target

train_x %>% class()
test_x %>% class()
```



```{r}
model_encoder <- keras_model_sequential()

model_encoder %>% 
  layer_dense(units = 512, activation = "relu", input_shape = ncol(train_x)) %>% 
  layer_dense(units = 256, activation = "relu") %>% 
  layer_dense(units = 8, activation = "relu", name = "embedding") %>% 
  layer_dense(units = 256, activation = "relu") %>% 
  layer_dense(units = 512, activation = "relu") %>% 
  layer_dense(units = ncol(train_x))

model_encoder %>% compile(
  loss = "mean_squared_error",
  optimizer = "adam"
)

summary(model_encoder)
```


```{r}
autoencoder_hist <- keras::fit(
  model_encoder,
  x = as.matrix(train_x),
  y = as.matrix(train_x),
  epochs = 100,
  batch_size = 32,
  validation_split = .8,
  options = callback_early_stopping(patience = 10)
)
```

```{r}
encoder

embeddings_model <- keras_model(
  
  inputs = encoder$input,
  outputs = get_layer(encoder, "embedding")$output
  
)

embeddings_model
```


```{r}
model_data <- predict(embeddings_model, train_x) %>% as.data.frame()
Target = train_y$Target
model_data <- cbind(model_data,Target)
```

```{r}
model <- multinom_reg(mode = "classification", penalty = 0, mixture = 0) %>% 
  fit(Target~., data = model_data)
```


```{r}
eval_set<- predict(embeddings_model, test_x) %>% as.data.frame()
Target = test_y$Target
eval_set <- cbind(eval_set, Target)

predict(model, eval_set %>% as_tibble()) %>% 
  conf_mat(truth = Target, estimate = .pred_class)
```